name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  SERVICE_NAME: "docker-gs-ping"
  REGISTRY_NAME: "type954"
  #HELM_REPO: ${{ env.SERVICE_NAME }}-helm-${{ env.TAG }}
  IMAGE_NAME: ${{ github.repository }}
  TAG: "dev"
  #COMMIT_ID: ${{ github.sha:0:7 }}
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout github repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Docker build
      run: docker build --tag ${{ env.SERVICE_NAME }}-${{ env.TAG }} .

    - name: Docker tag
      run: docker image tag ${{ env.SERVICE_NAME }}-${{ env.TAG }}:latest ${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}-${{ env.TAG }}:${GITHUB_SHA::7}

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker push
      run: docker push ${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}-${{ env.TAG }}:${GITHUB_SHA::7}
      
    - name: Checkout github helm chart
      uses: actions/checkout@v3
      with:
        repository: type954/${{ env.SERVICE_NAME }}-helm
        token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT
        #path: are-helm

    - name: values.yaml update
      run: |
        #sed -i "" "/^\([[:space:]]*tag: \).*/s//\1CCCCC/" $2 values.yaml
        sed -i 's/^\(\s*tag\s*:\s*\).*/\1'${GITHUB_SHA::7}'/' values.yaml
    - name: git add
      run: |
        git add ./values.yaml
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    
    - name: git status
      run: git status
    
    - name: git commit
      run: git commit -m "Pushed ${{ env.SERVICE_NAME }} Helm Chart:${GITHUB_SHA::7}"

    - name: git push
      run: git push
