name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  IMAGE_NAME: ${{ github.repository }}
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        #labels: ${{ steps.meta.outputs.labels }}
        
        
    - name: Update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'type954/${{ env.IMAGE_NAME }}-helm/values.yaml'
        propertyPath: 'deployment.image.tag'
        value: ${{ steps.image.outputs.version }}
        branch: deployment/${{ steps.image.outputs.version }}
        targetBranch: development
        createPR: true
        message: 'Update Image Version to ${{ steps.image.outputs.version }}'
